name: Code style & unit tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "poetry"
      - name: Set up Node.js
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          poetry install -n
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Code style
        run: |
          poetry run black --check handsdown --preview
          poetry run isort -c handsdown
      - name: Lint
        run: |
          poetry run flake8 handsdown
      - name: Typing
        run: |
          poetry run npx pyright
      - name: Test
        run: |
          poetry run pytest
